// Generated by the DSL transpiler -- do not edit (the source is the //@@dsl block below).

struct ScriptData
{
};

SCRIPT_EXPORT void OnSpawn(const ScriptContext* ctx, Entity* self, ScriptData* scriptData);
SCRIPT_EXPORT void OnDestroy(const ScriptContext* ctx, Entity* self, ScriptData* scriptData);
SCRIPT_EXPORT void Update(const ScriptContext* ctx, Entity* self, float deltaSeconds, ScriptData* scriptData);

SCRIPT_EXPORT void OnSpawn(const ScriptContext* ctx, Entity* self, ScriptData* scriptData)
{
	ctx->hudSetSlot(0, ctx->internString("Sword"), 0);
	ctx->hudSetSlot(1, ctx->internString("Bow"), 0);
	ctx->hudSetSlot(2, ctx->internString("Arrow"), 42);
	ctx->hudSetSlot(3, ctx->internString("Apple"), 5);
	ctx->hudSetSlot(4, ctx->internString("Torch"), 12);
	ctx->hudSelectSlot(0);
	ctx->hudSetBar(ctx->internString("Health"), 100.0f, 100.0f, glm::vec3(0.85f, 0.15f, 0.15f));
	ctx->hudSetBar(ctx->internString("Energy"), 100.0f, 100.0f, glm::vec3(0.15f, 0.55f, 0.9f));
	ctx->hudSetCounter(ctx->internString("Coins"), 128.0f, 0, glm::vec3(1.0f, 0.85f, 0.2f));
	ctx->logf(ctx->internString("HUD test OnSpawn"));
}

REGISTER_ON_SPAWN()

SCRIPT_EXPORT void OnDestroy(const ScriptContext* ctx, Entity* self, ScriptData* scriptData)
{
	ctx->hudClear(0);
}

REGISTER_ON_DESTROY()

SCRIPT_EXPORT void Update(const ScriptContext* ctx, Entity* self, float deltaSeconds, ScriptData* scriptData)
{
	float time = ctx->elapsedSeconds;
	float health = 50.0f + 50.0f * glm::sin(glm::radians(time * 90.0f));
	float energy = 50.0f + 50.0f * glm::sin(glm::radians(time * 75.0f + 180.0f));
	ctx->hudSetBar(ctx->internString("Health"), health, 100.0f, glm::vec3(0.85f, 0.15f, 0.15f));
	ctx->hudSetBar(ctx->internString("Energy"), energy, 100.0f, glm::vec3(0.15f, 0.55f, 0.9f));
}

REGISTER_UPDATE()

//@@dsl 1
//@
//@function OnSpawn()
//@	hud.setSlot(int slot = 0, string label = "Sword", int count = 0)
//@	hud.setSlot(int slot = 1, string label = "Bow", int count = 0)
//@	hud.setSlot(int slot = 2, string label = "Arrow", int count = 42)
//@	hud.setSlot(int slot = 3, string label = "Apple", int count = 5)
//@	hud.setSlot(int slot = 4, string label = "Torch", int count = 12)
//@	hud.selectSlot(int slot = 0)
//@	hud.setBar(string name = "Health", float value = 100.0, float maxValue = 100.0, vec3 color = vec3(0.85, 0.15, 0.15))
//@	hud.setBar(string name = "Energy", float value = 100.0, float maxValue = 100.0, vec3 color = vec3(0.15, 0.55, 0.9))
//@	hud.setCounter(string name = "Coins", float value = 128.0, int decimals = 0, vec3 color = vec3(1.0, 0.85, 0.2))
//@	printf(string format = "HUD test OnSpawn")
//@end
//@
//@function OnDestroy()
//@	hud.clear()
//@end
//@
//@function Update(float deltaSeconds)
//@	float time = world.time
//@	float health = 50 + 50 * math.sin(float angleDeg = time * 90)
//@	float energy = 50 + 50 * math.sin(float angleDeg = time * 75 + 180)
//@	hud.setBar(string name = "Health", float value = health, float maxValue = 100.0, vec3 color = vec3(0.85, 0.15, 0.15))
//@	hud.setBar(string name = "Energy", float value = energy, float maxValue = 100.0, vec3 color = vec3(0.15, 0.55, 0.9))
//@end
//@@end
