// Generated by the DSL transpiler -- do not edit (the source is the //@@dsl block below).

struct ScriptData
{
};

SCRIPT_EXPORT void Update(const ScriptContext* ctx, Entity* self, float deltaSeconds, ScriptData* scriptData);

SCRIPT_EXPORT void Update(const ScriptContext* ctx, Entity* self, float deltaSeconds, ScriptData* scriptData)
{
	self->pos = ctx->cameraPosition;
	self->scale = ctx->cameraFar / 100.0f;
}

REGISTER_UPDATE()

//@@dsl 1
//@
//@function Update(float deltaSeconds)
//@	self.pos = world.camera.position
//@	self.scale = world.camera.farPlane / 100.0
//@end
//@@end
