// Generated by the DSL transpiler -- do not edit (the source is the //@@dsl block below).

struct ScriptData
{
	SceneComponent* scene;
	glm::vec3 lastPos = glm::vec3();
};

SCRIPT_EXPORT unsigned int ScriptDataSize(void) { return sizeof(ScriptData); }
SCRIPT_EXPORT unsigned int ScriptDataLayoutId(void) { return 104093501u; }
REGISTER_SCRIPT_DATA_SIZE()

SCRIPT_EXPORT unsigned int ScriptRequiredComponents(void) { return (1u << 0); }
REGISTER_SCRIPT_REQUIRED_COMPONENTS()

SCRIPT_EXPORT void OnSpawn(const ScriptContext* ctx, Entity* self, ScriptData* scriptData);
SCRIPT_EXPORT void Update(const ScriptContext* ctx, Entity* self, float deltaSeconds, ScriptData* scriptData);

SCRIPT_EXPORT void OnSpawn(const ScriptContext* ctx, Entity* self, ScriptData* scriptData)
{

}

REGISTER_ON_SPAWN()

SCRIPT_EXPORT void Update(const ScriptContext* ctx, Entity* self, float deltaSeconds, ScriptData* scriptData)
{

}

REGISTER_UPDATE()

//@@dsl 1
//@@require SceneComponent
//@@data vec3 lastPos
//@
//@function OnSpawn()
//@	
//@end
//@
//@function Update(float deltaSeconds)
//@	
//@end
//@@end
